CREATE DATABASE IF NOT EXISTS sr03_devoir2;

USE sr03_devoir2;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS chat;
DROP TABLE IF EXISTS chat_user;

CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    login VARCHAR(20) NOT NULL,
	fname VARCHAR(20) NOT NULL,
	lname VARCHAR(20) NOT NULL,
	email VARCHAR(45) NOT NULL,
	gender VARCHAR(10) DEFAULT 'male',
	pwd VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE chat (
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(30) NOT NULL,
	owner_id INT NOT NULL,
	description VARCHAR(200),
	create_time TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE chat_user (
	id INT NOT NULL AUTO_INCREMENT,
	chat_id INT NOT NULL,
	user_id INT NOT NULL,
	PRIMARY KEY (id)
);
