CREATE DATABASE IF NOT EXISTS sr03_devoir2;

USE sr03_devoir2;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
    id INT NOT NULL AUTO_INCREMENT,
    login VARCHAR(20) NOT NULL,
	fname VARCHAR(20) NOT NULL,
	lname VARCHAR(20) NOT NULL,
	email VARCHAR(45) NOT NULL,
	gender VARCHAR(10) DEFAULT 'male',
	pwd VARCHAR(45) NOT NULL,
    PRIMARY KEY (id)
);
